### ISSUE TITLE
chapter8_quesiton2_book(file modes)

### ISSUE THREAD

**Issue by Ocxs** [Ocxs/Cpp-Primer#10]
In chapter 8.2.2 File modes

> - out may be set only for an ofstream or fstream object
> - in may be set only for an ifstream or fstream object

这里may be怎么翻译？我看中文版翻译是：

> - 只可以对ofstream 或 fstream对象设定out模式
> - 只可以对 ifstream 或 fstream 对象设定in模式

```
if(中文版翻译是对的话）
｛
       我在vs2013里这样写：`ofstream out1("test.txt", ofstream::in | ofstream::out);`
 不知道这是为什么？
｝
```

然后紧接着又说为了保留以out模式打开的文件的内容，我们必须同时指定app模式，或者同时指定in模式。
我就尝试用第二种方法试了一下，

```
fstream inout("test.txt",fstream::out | fstream::in);
inout << "test " << endl;
```

文本里的原来内容是

```
11  
22  
33
```

但是通过这种方式后变成`test`。没有预期保留打开文件内容的效果，是我代码写错了吗？如果写错了该怎么写呢？

**Comment by pezy** [comment]
> 这里may be怎么翻译？我看中文版翻译是：

英文版更准确一些。这些 mode 本质只是一个宏，起到标识作用，所以你那么写也行，只是如果你尝试用输出流写入东西的话，可能无效罢了。

> 是我代码写错了吗？如果写错了该怎么写呢？

错了，用 `fstream::in | fstream::app`

**Comment by Ocxs** [comment]
@pezy Thx!最近把系统换成linux，然后各种不习惯，连装软件都要用命令行，快崩溃了，请问有什么学习Linux的建议吗？我用的是CentOS7.0 :cry:

**Comment by pezy** [comment]
建议看一本书：http://book.douban.com/subject/1400361/

**Comment by Ocxs** [comment]
@pezy 多谢!
