### ISSUE TITLE
chapter4_quesiton1_book(returns a pointer as rvalue)

### ISSUE THREAD

**Issue by Ocxs** [Ocxs/Cpp-Primer#2]
In _C++ Primer Fifh Editon_

> The address-of operator (§ 2.3.2, p. 52) requires an lvalue operand and returns a pointer to its operand as an rvalue.

why did it return a pointer to its operand as an **rvalue** rather than a lvalue？

BTW，what's the meaning of  "**yield**" in computer science ,how to understand it ?(I always see this word , I look for it in YoudDao ,but its explanation is not good .)

**Comment by pezy** [comment]
Please See [What are rvalues, lvalues, xvalues, glvalues, and prvalues?](http://stackoverflow.com/questions/3601602/what-are-rvalues-lvalues-xvalues-glvalues-and-prvalues)
- lvalue: object or functions(return lvalue reference)
- xvalue: preexited object, functions(return rvalue reference)
- glvalue: generalized lvalue, lvalue + xvalue
- rvalue: xvalue + temporary object or subobject thereof + a value that is not associated with an object
- prvalue: rvalue - xvalue.

``` cpp
int i = 0;
int *p = &i;
         ^^
```

`i` and `p` are certainly `lvalue`. (we can identify them by their name.) But, `&i`, we can't identify it, we just know it's value (maybe like `0xds689932`) it's a **temporary object**. When assignment finished, it   will disappear, we just can find `p`.

---

we can image as following:
- `lvalue`: like a strongbox, you have key, and can open it anytime.
- `rvalue`: like a bank, you can get your money from it. But you never know where your money stored exactly.

**Comment by pezy** [comment]
> what's the meaning of "yield" in computer science

just common meaning, **produce** or **provide**, and **designates** I think.

**Comment by Ocxs** [comment]
@pezy  Thx a lot ! :+1: :smile:
