### ISSUE TITLE
chapter6_quesiton2_book(const char* and string)

### ISSUE THREAD

**Issue by Ocxs** [Ocxs/Cpp-Primer#3]
In *C++ Primer Fifth Edition *：
about at page183 (English Book)

> `fact ("hello");`

As book says,the type of  `"hello"` is `const char *`.  Then can we say that the type of  `"hello"` is `string`?
(IMO ,we can't)

**Comment by pezy** [comment]
Exactly, `"hello"` is a string literal, 2.1.3(p. 39):

> The type of a string literal is **array of constant chars**.

and in 3.5.4(p. 122):

> Character string literals are an instance of a more general construct that C++ inherits
> from C: **C-style character strings**.
> C-style strings are not a type. Instead, they are
> a convention for how to represent and use character strings. Strings that follow this
> convention are stored in character arrays and are null terminated. By null-
> terminated we mean that the last character in the string is followed by a null
> character ('\0'). Ordinarily we use pointers to manipulate these strings.

---

But we can use `const char *` in which implicit conversions happen. You will see this content in 7.5.

> The `string` constructor that takes a single parameter of type `const char*` (3.2.1, p. 84) is not explicit.

So don't worry about it. You will have a deep understanding in Chapter 7.

**Comment by Ocxs** [comment]
看了您的Exercise 7.51的回答

> ```
> void setYourName(std::string); // declaration.
> setYourName("pezy"); // just fine.
> ```

因为

> The string constructor that takes a single parameter of type const char\* (3.2.1, p. 84) is not explicit.

所以才能让`"pezy"`发生隐式的类类型转换，转换成string类型？那这样的话，岂不是还是说`"hello"`是`const char *`吗？（其实我读完这一章，感觉并没有更深的理解啊  :cry: )

**Comment by pezy** [comment]
> 所以才能让"pezy"发生隐式的类类型转换，转换成string类型？

是的。

> 那这样的话，岂不是还是说"hello"是const char *吗？

。。。上面不是说了吗，它的类别是 **C-style character strings** 吗？而 "hello"显然是一个 prvalue, 我们无从改变它，编译器便为其加上了 `const` 属性，所以从编译器的角度来看，其类型为 `const char *`.

> we say that the type of "hello" is string

当然是 No，可能我说多了，反而乱了。我只是觉得你会产生这样的疑惑（觉得是 “string”）是因为 `setYourName("pezy");` 表面上给你的错觉。而我说你会有更深的理解，是希望你明白这其中经历的隐式转换罢了。。。 :sob:

**Comment by Ocxs** [comment]
@pezy 额，我在第一次提问的时候就说了自己的观点啊

> (IMO ,we can't)

我认为不能说`”hello“`是`string`类型，因为`string`是一个类类型，`”hello“`只是一个字面值常量，不是一个对象，所以不能叫做`string`类型，应该称其类型是`const char*`，如果`str = "hello";`，**我们可以称str是string类型吧？** 之所以会问`string`还是`const char*`是因为在我看primer这本书之前，我们只学过C++，没学过C，当时老师教也就是教了`string`，没有说`const char*`(我看了primer之后才知道竟然还有`const char *` :sob:  ），但是看了primer之后，才知道string是一个类类型，然后才会有点纠结，说出来让您给我开导一番！ :smile:  
那现在根据你说的，我总结一下，**就是`”hello“`是`const char*`类型，不是`string`类型，但是可以隐式的转换成`string`类型**

**Comment by pezy** [comment]
> 就是”hello“是const char*类型，不是string类型，但是可以隐式的转换成string类型

yes

**Comment by Ocxs** [comment]
@pezy 那这句话对吗？

> 如果str = "hello";，我们可以称str是string类型吧？

**Comment by pezy** [comment]
``` cpp
const char *str = "hello";
std::string str = "hello";
```

**Comment by Ocxs** [comment]
@pezy  Thx a lot ! :smile:
