### ISSUE TITLE
chapter7_quesiton1_book(Defining static Members)

### ISSUE THREAD

**Issue by Ocxs** [Ocxs/Cpp-Primer#8]
chapter 7.6 Defining static Members Tips

> As with any class member, when we refer to a class static member outside the class body, we must specify the class in which the member is defined. The static keyword, however, is used only on the declaration inside the class body.

书上说最好把静态数据成员的定义与**非内联函数**的定义放在一起。

chapter 7.3.1 Making Members inline

> For the same reasons that we define inline functions in headers (§ 6.5.2, p. 240), inline member functions should be defined in the same header as the corresponding class definition.

根据这上面说的，是不是我们在定义一个类的时候放在头文件中，如果有内联函数直接放在类的定义里，然后其他的成员函数的定义重新新建一个cpp文件（要包含类定义的头文件），在这个新建的cpp文件里定义成员函数?

**Comment by pezy** [comment]
> 书上说最好把静态数据成员的定义与非内联函数的定义放在一起。

不太明白你的意思。你引用的原文，讲的是静态成员函数的实现可以放到 class 外面，但 `static` 关键字，只能出现在 class body 里面。

> 如果有内联函数直接放在类的定义里，然后其他的成员函数的定义重新新建一个cpp文件（要包含类定义的头文件），在这个新建的cpp文件里定义成员函数?

我理解书上的意思啊，是建议将 **内联成员函数** 的 declaration 放到 class body 里面（加上 inline 关键字），然后将 definition 也放到同一个 .h 头文件中（但不在 class body 里面）。原因和 **普通的内联函数**一致：

> Unlike other functions, inline and constexpr functions may be defined multiple
> times in the program. **After all, the compiler needs the definition, not just the
> declaration, in order to expand the code. However, all of the definitions of a given
> inline or constexpr must match exactly.** As a result, inline and constexpr
> functions normally are defined in headers.

你好像也是这个意思。但你又提到其他成员函数，我有点疑惑这有何关系。对于普通的成员函数，通常在 class body 里面 declaration ，在 .cpp 文件里 definition.

**Comment by Ocxs** [comment]
@pezy 谢谢。按照你说的:建议在class body里声明内联函数，class body外定义，都在同一个.h文件中。这种方式我理解了，那我说的直接将定义也放入class body中应该也行，看书上有时候一句return也是直接放入class body里定义的。

**Comment by pezy** [comment]
恩，也行
