### ISSUE TITLE
chapter8_quesiton1_book(No Copy or Assign for IO Objects)

### ISSUE THREAD

**Issue by Ocxs** [Ocxs/Cpp-Primer#9]
In chapter 8.1.1 No Copy or Assign for IO Objects

> ```
> ofstream out1, out2;
> out1 = out2;                //不能对流对象赋值
> ofstream print(ofstream);           //不能初始化ofstream参数
> out2 = print(out2);         //不能拷贝流对象
> ```

问题1：
对于`ofstream print(ofstream);`说是“不能初始化ofstream参数”，这句话的意思是不是说，当调用print函数时，传递实参进来时，由于流对象不能拷贝和赋值，所以导致初始化失败？

问题2：那如果改成这样 `ofstream print(ofstream&);`应该就不会有问题1的那种错误了吧？

问题3：对于`out2 = print(out2);`书上说的错误是：”不能拷贝流对象“。但是我觉得错误应该是：由于out2是流对象，所以不应该被赋值，何来拷贝一说呢？难道说书上默认这里的print函数自带拷贝功能？将参数的流对象拷贝给另外一个流对象？

以上。

**Comment by pezy** [comment]
> 由于流对象不能拷贝和赋值，所以导致初始化失败？

是的，这个你会在 13 章了解到一个叫 拷贝构造函数的概念，本质原因：IO types 禁用了拷贝构造函数。

> 13.1.6. Preventing Copies
> For example, the iostream classes prevent copying to
> avoid letting multiple objects write to or read from the same IO buffer. It might seem
> that we could prevent copies by not defining the copy-control members.
> 
> 那如果改成这样 ofstream print(ofstream&);应该就不会有问题1的那种错误了吧？

也不行，因为 `ofstream` 根本没有这样的构造函数。（同样是13章，你可以了解到传递右值是被允许的）

> 由于out2是流对象，所以不应该被赋值，何来拷贝一说呢？难道说书上默认这里的print函数自带拷贝功能？将参数的流对象拷贝给另外一个流对象？

你说的其实也对。但 `=` 赋值本质上走的是 `Copy-Assignment Operator` ，其本质还是 copy，所以书上这么说也没什么错。建议不要过分纠结。。
